# Generated by Django 4.0.3 on 2022-03-07 22:20

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctors_name', models.CharField(max_length=30)),
                ('Doctors_surname', models.CharField(max_length=50)),
                ('Doctors_middle_name', models.CharField(max_length=50)),
                ('Doctors_photo', models.ImageField(upload_to='../static/images/doctors_images')),
                ('Doctors_about', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Доктора',
                'verbose_name_plural': 'Доктора',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback_name', models.CharField(max_length=50)),
                ('Feedback_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gallery_title', models.CharField(max_length=100)),
                ('Gallery_photo_gallery', models.ImageField(upload_to='../static/images/gallery_images')),
            ],
            options={
                'verbose_name': 'Галерея работ',
                'verbose_name_plural': 'Галерея работ',
            },
        ),
        migrations.CreateModel(
            name='Instagram_Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instagram_Links_title', models.CharField(max_length=100)),
                ('Instagram_Links_images', models.ImageField(upload_to='../static/images/instagram_links_images')),
                ('Instagram_Links_link', models.URLField()),
            ],
            options={
                'verbose_name': 'Наш инстаграм',
                'verbose_name_plural': 'Наш инстаграм',
            },
        ),
        migrations.CreateModel(
            name='Make_An_Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Make_An_Appointment_name', models.CharField(max_length=50)),
                ('Make_An_Appointment_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('Make_An_Appointment_mail', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Запись на приём',
                'verbose_name_plural': 'Запись на приём',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reviews_yandex', models.CharField(max_length=50)),
                ('Reviews_google', models.CharField(max_length=50)),
                ('Reviews_zoon', models.CharField(max_length=50)),
                ('Reviews_spr', models.CharField(max_length=50)),
                ('Reviews_prodoctorov', models.CharField(max_length=50)),
                ('Reviews_yell', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Services_orthodontics', models.CharField(max_length=50)),
                ('Services_implantology', models.CharField(max_length=50)),
                ('Services_functional_dentistry', models.CharField(max_length=50)),
                ('Services_orthopedics', models.CharField(max_length=50)),
                ('Services_therapy', models.CharField(max_length=50)),
                ('Services_periodontology', models.CharField(max_length=50)),
                ('Services_surgery', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stocks_title', models.CharField(max_length=100)),
                ('Stocks_gallery', models.ImageField(upload_to='../static/images/stocks_gallery_images')),
            ],
            options={
                'verbose_name': 'Акции',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Functional_Dentistry',
            fields=[
                ('Functional_Dentistry_functional_dentistry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AvitaDentApp.services')),
                ('Functional_Dentistry_image', models.ImageField(upload_to='../static/images/functional_dentistry_images')),
                ('Functional_Dentistry_title', models.CharField(max_length=50)),
                ('Functional_Dentistry_about', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Функциональная стоматология',
                'verbose_name_plural': 'Функциональная стоматология',
            },
        ),
        migrations.CreateModel(
            name='Implantology',
            fields=[
                ('Implantology_implantology', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AvitaDentApp.services')),
                ('Implantology_image', models.ImageField(upload_to='../static/images/implantology_images')),
                ('Implantology_title', models.CharField(max_length=50)),
                ('Implantology_about', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Имплантология',
                'verbose_name_plural': 'Имплантология',
            },
        ),
        migrations.CreateModel(
            name='Orthodontics',
            fields=[
                ('Orthodontics_orthodontics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AvitaDentApp.services')),
                ('Orthodontics_image', models.ImageField(upload_to='../static/images/orthodontics_images')),
                ('Orthodontics_title', models.CharField(max_length=50)),
                ('Orthodontics_about', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Ортодонтия',
                'verbose_name_plural': 'Ортодонтия',
            },
        ),
        migrations.CreateModel(
            name='Orthopedics',
            fields=[
                ('Orthopedics_orthopedics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AvitaDentApp.services')),
                ('Orthopedics_image', models.ImageField(upload_to='../static/images/orthopedics_images')),
                ('Orthopedics_title', models.CharField(max_length=50)),
                ('Orthopedics_about', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Ортопедия',
                'verbose_name_plural': 'Ортопедия',
            },
        ),
        migrations.CreateModel(
            name='Periodontology',
            fields=[
                ('Periodontology_periodontology', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AvitaDentApp.services')),
                ('Periodontology_image', models.ImageField(upload_to='../static/images/periodontology_images')),
                ('Periodontology_title', models.CharField(max_length=50)),
                ('Periodontology_about', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Парадонтология',
                'verbose_name_plural': 'Парадонтология',
            },
        ),
        migrations.CreateModel(
            name='Reviews_Google',
            fields=[
                ('Reviews_Google_google', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AvitaDentApp.reviews')),
                ('Reviews_Google_full_name', models.CharField(max_length=50)),
                ('Reviews_Google_review', models.CharField(max_length=1000)),
                ('Reviews_Google_date', models.DateField()),
                ('Reviews_Google_source', models.URLField()),
                ('Reviews_Google_stars', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Отзывы Гугл',
                'verbose_name_plural': 'Отзывы Гугл',
            },
        ),
        migrations.CreateModel(
            name='Reviews_Prodoctorov',
            fields=[
                ('Reviews_Prodoctorov_prodoctorov', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AvitaDentApp.reviews')),
                ('Reviews_Prodoctorov_full_name', models.CharField(max_length=50)),
                ('Reviews_Prodoctorov_review', models.CharField(max_length=1000)),
                ('Reviews_Prodoctorov_date', models.DateField()),
                ('Reviews_Prodoctorov_source', models.URLField()),
                ('Reviews_Prodoctorov_stars', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Отзывы Продокторов',
                'verbose_name_plural': 'Отзывы Продокторов',
            },
        ),
        migrations.CreateModel(
            name='Reviews_Spr',
            fields=[
                ('Reviews_Spr_spr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AvitaDentApp.reviews')),
                ('Reviews_Spr_full_name', models.CharField(max_length=50)),
                ('Reviews_Spr_review', models.CharField(max_length=1000)),
                ('Reviews_Spr_date', models.DateField()),
                ('Reviews_Spr_source', models.URLField()),
                ('Reviews_Spr_stars', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Отзывы СПР',
                'verbose_name_plural': 'Отзывы СПР',
            },
        ),
        migrations.CreateModel(
            name='Reviews_Yandex',
            fields=[
                ('Reviews_Yandex_yandex', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AvitaDentApp.reviews')),
                ('Reviews_Yandex_full_name', models.CharField(max_length=50)),
                ('Reviews_Yandex_review', models.CharField(max_length=1000)),
                ('Reviews_Yandex_date', models.DateField()),
                ('Reviews_Yandex_source', models.URLField()),
                ('Reviews_Yandex_stars', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Отзывы Яндекс',
                'verbose_name_plural': 'Отзывы Яндекс',
            },
        ),
        migrations.CreateModel(
            name='Reviews_Yell',
            fields=[
                ('Reviews_Yell_yell', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AvitaDentApp.reviews')),
                ('Reviews_Yell_full_name', models.CharField(max_length=50)),
                ('Reviews_Yell_review', models.CharField(max_length=1000)),
                ('Reviews_Yell_date', models.DateField()),
                ('Reviews_Yell_source', models.URLField()),
                ('Reviews_Yell_stars', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Отзывы Йелл',
                'verbose_name_plural': 'Отзывы Йелл',
            },
        ),
        migrations.CreateModel(
            name='Reviews_Zoon',
            fields=[
                ('Reviews_Zoon_zoon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AvitaDentApp.reviews')),
                ('Reviews_Zoon_full_name', models.CharField(max_length=50)),
                ('Reviews_Zoon_review', models.CharField(max_length=1000)),
                ('Reviews_Zoon_date', models.DateField()),
                ('Reviews_Zoon_source', models.URLField()),
                ('Reviews_Zoon_stars', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Отзывы Зун',
                'verbose_name_plural': 'Отзывы Зун',
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('Surgery_surgery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AvitaDentApp.services')),
                ('Surgery_image', models.ImageField(upload_to='../static/images/surgery_images')),
                ('Surgery_title', models.CharField(max_length=50)),
                ('Surgery_about', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Хирургия',
                'verbose_name_plural': 'Хирургия',
            },
        ),
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('Therapy_therapy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AvitaDentApp.services')),
                ('Therapy_image', models.ImageField(upload_to='../static/images/therapy_images')),
                ('Therapy_title', models.CharField(max_length=50)),
                ('Therapy_about', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Терапия',
                'verbose_name_plural': 'Терапия',
            },
        ),
    ]
