# Generated by Django 4.0.3 on 2022-03-18 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actions_title', models.CharField(max_length=100, verbose_name='Название акции')),
                ('Actions_webp', models.ImageField(upload_to='images/actions_gallery_images/webp', verbose_name='WEBP-изображение акции')),
                ('Actions_gallery', models.ImageField(upload_to='images/actions_gallery_images', verbose_name='Обычное изображение акции')),
            ],
            options={
                'verbose_name': 'Акции',
                'verbose_name_plural': 'Акции',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='reviews_google',
            name='Reviews_Google_google',
        ),
        migrations.RemoveField(
            model_name='reviews_prodoctorov',
            name='Reviews_Prodoctorov_prodoctorov',
        ),
        migrations.RemoveField(
            model_name='reviews_spr',
            name='Reviews_Spr_spr',
        ),
        migrations.RemoveField(
            model_name='reviews_yandex',
            name='Reviews_Yandex_yandex',
        ),
        migrations.RemoveField(
            model_name='reviews_yell',
            name='Reviews_Yell_yell',
        ),
        migrations.RemoveField(
            model_name='reviews_zoon',
            name='Reviews_Zoon_zoon',
        ),
        migrations.DeleteModel(
            name='Stocks',
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['id'], 'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['id'], 'verbose_name': 'Галерея работ', 'verbose_name_plural': 'Галерея работ'},
        ),
        migrations.AlterModelOptions(
            name='orthodontics',
            options={'ordering': ['Orthodontics_datetime'], 'verbose_name': 'Ортодонтия', 'verbose_name_plural': 'Ортодонтия'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['id'], 'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['id'], 'verbose_name': 'Услуги', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='Reviews_google',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='Reviews_prodoctorov',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='Reviews_spr',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='Reviews_yandex',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='Reviews_yell',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='Reviews_zoon',
        ),
        migrations.RemoveField(
            model_name='services',
            name='Services_functional_dentistry',
        ),
        migrations.RemoveField(
            model_name='services',
            name='Services_implantology',
        ),
        migrations.RemoveField(
            model_name='services',
            name='Services_orthodontics',
        ),
        migrations.RemoveField(
            model_name='services',
            name='Services_orthopedics',
        ),
        migrations.RemoveField(
            model_name='services',
            name='Services_periodontology',
        ),
        migrations.RemoveField(
            model_name='services',
            name='Services_surgery',
        ),
        migrations.RemoveField(
            model_name='services',
            name='Services_therapy',
        ),
        migrations.AddField(
            model_name='gallery',
            name='Gallery_webp',
            field=models.ImageField(blank=True, null=True, upload_to='images/gallery_gallery_images/webp', verbose_name='WEBP-изображение галереи'),
        ),
        migrations.AddField(
            model_name='orthodontics',
            name='Orthodontics_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания записи'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='Reviews_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата отзыва'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='Reviews_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Автор отзыва'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='Reviews_source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Источник отзыва'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='Reviews_text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='services',
            name='Services_gallery',
            field=models.ImageField(blank=True, null=True, upload_to='images/services_gallery_images', verbose_name='Обычное изображение услуги'),
        ),
        migrations.AddField(
            model_name='services',
            name='Services_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='services',
            name='Services_webp',
            field=models.ImageField(blank=True, null=True, upload_to='images/services_gallery_images/webp', verbose_name='WEBP-изображение услуги'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='Doctors_photo',
            field=models.ImageField(upload_to='images/doctors_images'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Feedback_phone',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='functional_dentistry',
            name='Functional_Dentistry_image',
            field=models.ImageField(upload_to='images/functional_dentistry_images'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='Gallery_photo_gallery',
            field=models.ImageField(upload_to='images/gallery_gallery_images', verbose_name='Обычное изображение галереи'),
        ),
        migrations.AlterField(
            model_name='implantology',
            name='Implantology_image',
            field=models.ImageField(upload_to='images/implantology_images'),
        ),
        migrations.AlterField(
            model_name='instagram_links',
            name='Instagram_Links_images',
            field=models.ImageField(upload_to='images/instagram_links_images'),
        ),
        migrations.AlterField(
            model_name='orthodontics',
            name='Orthodontics_image',
            field=models.ImageField(upload_to='images/orthodontics_images'),
        ),
        migrations.AlterField(
            model_name='orthopedics',
            name='Orthopedics_image',
            field=models.ImageField(upload_to='images/orthopedics_images'),
        ),
        migrations.AlterField(
            model_name='periodontology',
            name='Periodontology_image',
            field=models.ImageField(upload_to='images/periodontology_images'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='Surgery_image',
            field=models.ImageField(upload_to='images/surgery_images'),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='Therapy_image',
            field=models.ImageField(upload_to='images/therapy_images'),
        ),
        migrations.DeleteModel(
            name='Reviews_Google',
        ),
        migrations.DeleteModel(
            name='Reviews_Prodoctorov',
        ),
        migrations.DeleteModel(
            name='Reviews_Spr',
        ),
        migrations.DeleteModel(
            name='Reviews_Yandex',
        ),
        migrations.DeleteModel(
            name='Reviews_Yell',
        ),
        migrations.DeleteModel(
            name='Reviews_Zoon',
        ),
    ]
