# Generated by Django 4.0.3 on 2022-03-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0002_actions_delete_stocks_alter_services_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Feedback_phone',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
