# Generated by Django 4.0.3 on 2022-03-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0002_actions_remove_reviews_google_reviews_google_google_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orthodontics',
            name='Orthodontics_webp',
            field=models.ImageField(blank=True, null=True, upload_to='images/Orthodontics_webp/webp', verbose_name='WEBP-изображение страницы Ортодонтия'),
        ),
        migrations.AlterField(
            model_name='orthodontics',
            name='Orthodontics_image',
            field=models.ImageField(upload_to='images/Orthodontics_images', verbose_name='Обычное изображение страницы Ортодонтия'),
        ),
    ]
