# Generated by Django 4.0.3 on 2022-03-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0003_alter_stocks_stocks_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='Doctors_photo',
            field=models.ImageField(upload_to='images/doctors_images'),
        ),
        migrations.AlterField(
            model_name='functional_dentistry',
            name='Functional_Dentistry_image',
            field=models.ImageField(upload_to='images/functional_dentistry_images'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='Gallery_photo_gallery',
            field=models.ImageField(upload_to='images/gallery_images'),
        ),
        migrations.AlterField(
            model_name='implantology',
            name='Implantology_image',
            field=models.ImageField(upload_to='images/implantology_images'),
        ),
        migrations.AlterField(
            model_name='instagram_links',
            name='Instagram_Links_images',
            field=models.ImageField(upload_to='images/instagram_links_images'),
        ),
        migrations.AlterField(
            model_name='orthodontics',
            name='Orthodontics_image',
            field=models.ImageField(upload_to='images/orthodontics_images'),
        ),
        migrations.AlterField(
            model_name='orthopedics',
            name='Orthopedics_image',
            field=models.ImageField(upload_to='images/orthopedics_images'),
        ),
        migrations.AlterField(
            model_name='periodontology',
            name='Periodontology_image',
            field=models.ImageField(upload_to='images/periodontology_images'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='Surgery_image',
            field=models.ImageField(upload_to='images/surgery_images'),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='Therapy_image',
            field=models.ImageField(upload_to='images/therapy_images'),
        ),
    ]
