# Generated by Django 4.0.3 on 2022-03-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0003_alter_feedback_feedback_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['id'], 'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['id'], 'verbose_name': 'Галерея работ', 'verbose_name_plural': 'Галерея работ'},
        ),
        migrations.AddField(
            model_name='gallery',
            name='Gallery_webp',
            field=models.ImageField(blank=True, null=True, upload_to='images/gallery_gallery_images/webp', verbose_name='WEBP-изображение галереи'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='Gallery_photo_gallery',
            field=models.ImageField(upload_to='images/gallery_gallery_images', verbose_name='Обычное изображение галереи'),
        ),
    ]
