# Generated by Django 4.0.3 on 2022-03-18 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0003_orthodontics_orthodontics_webp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orthodontics',
            old_name='Orthodontics_orthodontics',
            new_name='Orthodontics_Services',
        ),
    ]
