# Generated by Django 4.0.3 on 2022-03-18 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0004_rename_orthodontics_orthodontics_orthodontics_orthodontics_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orthodontics',
            name='Orthodontics_Services',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AvitaDentApp.services', verbose_name='Связь с моделью УСЛУГИ'),
        ),
        migrations.AlterField(
            model_name='orthodontics',
            name='Orthodontics_about',
            field=models.CharField(max_length=1000, verbose_name='Об Ортодонтии'),
        ),
        migrations.AlterField(
            model_name='orthodontics',
            name='Orthodontics_title',
            field=models.CharField(max_length=50, verbose_name='Название Ортодонтической УСЛУГИ'),
        ),
    ]
