# Generated by Django 4.0.3 on 2022-03-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0004_alter_feedback_options_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['id'], 'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='Reviews_google',
            new_name='Reviews_date',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='Reviews_prodoctorov',
            new_name='Reviews_name',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='Reviews_spr',
            new_name='Reviews_source',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='Reviews_yandex',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='Reviews_yell',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='Reviews_zoon',
        ),
        migrations.AddField(
            model_name='reviews',
            name='Reviews_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
