# Generated by Django 4.0.3 on 2022-03-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0004_alter_doctors_doctors_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actions_title', models.CharField(max_length=100, verbose_name='Заголовок акции')),
                ('Actions_gallery', models.ImageField(upload_to='images/actions_gallery_images')),
            ],
            options={
                'verbose_name': 'Акции',
                'verbose_name_plural': 'Акции',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Stocks',
        ),
    ]
