# Generated by Django 4.0.3 on 2022-03-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0005_alter_reviews_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='Reviews_date',
            field=models.CharField(max_length=50, verbose_name='Дата отзыва'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='Reviews_name',
            field=models.CharField(max_length=50, verbose_name='Автор отзыва'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='Reviews_source',
            field=models.CharField(max_length=50, verbose_name='Источник отзыва'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='Reviews_text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст отзыва'),
        ),
    ]
