# Generated by Django 4.0.3 on 2022-03-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0005_actions_delete_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='Actions_webp',
            field=models.ImageField(blank=True, null=True, upload_to='images/actions_gallery_images/webp'),
        ),
    ]
