# Generated by Django 4.0.3 on 2022-03-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0006_actions_actions_webp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='Actions_title',
            field=models.CharField(max_length=100, verbose_name='Название акции'),
        ),
        migrations.AlterField(
            model_name='services',
            name='Services_functional_dentistry',
            field=models.CharField(max_length=50, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='services',
            name='Services_implantology',
            field=models.CharField(max_length=50, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='services',
            name='Services_orthodontics',
            field=models.CharField(max_length=50, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='services',
            name='Services_orthopedics',
            field=models.CharField(max_length=50, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='services',
            name='Services_periodontology',
            field=models.CharField(max_length=50, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='services',
            name='Services_surgery',
            field=models.CharField(max_length=50, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='services',
            name='Services_therapy',
            field=models.CharField(max_length=50, verbose_name='Название услуги'),
        ),
    ]
