# Generated by Django 4.0.3 on 2022-03-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0006_remove_orthodontics_orthodontics_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orthodontics',
            name='Orthodontics_IntegerField',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер для ручного внесения'),
        ),
        migrations.AlterField(
            model_name='orthodontics',
            name='Orthodontics_webp',
            field=models.ImageField(blank=True, null=True, upload_to='images/Orthodontics_images/webp', verbose_name='WEBP-изображение страницы Ортодонтия'),
        ),
    ]
