# Generated by Django 4.0.3 on 2022-03-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0007_orthodontics_orthodontics_integerfield_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orthodontics',
            options={'ordering': ['Orthodontics_IntegerField'], 'verbose_name': 'Ортодонтия', 'verbose_name_plural': 'Ортодонтия'},
        ),
        migrations.RemoveField(
            model_name='orthodontics',
            name='Orthodontics_datetime',
        ),
    ]
