# Generated by Django 4.0.3 on 2022-03-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0008_alter_services_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='Services_gallery',
            field=models.ImageField(blank=True, null=True, upload_to='images/services_gallery_images', verbose_name='Обычное изображение услуги'),
        ),
        migrations.AddField(
            model_name='services',
            name='Services_webp',
            field=models.ImageField(blank=True, null=True, upload_to='images/actions_gallery_images/webp', verbose_name='WEBP-изображение услуги'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='Actions_gallery',
            field=models.ImageField(blank=True, null=True, upload_to='images/actions_gallery_images', verbose_name='Обычное изображение акции'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='Actions_webp',
            field=models.ImageField(blank=True, null=True, upload_to='images/actions_gallery_images/webp', verbose_name='WEBP-изображение акции'),
        ),
        migrations.AlterField(
            model_name='services',
            name='Services_title',
            field=models.CharField(max_length=100, verbose_name='Название услуги'),
        ),
    ]
