# Generated by Django 4.0.3 on 2022-03-18 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0009_remove_implantology_implantology_about_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='functional_dentistry',
            options={'ordering': ['Functional_Dentistry_IntegerField'], 'verbose_name': 'Функциональная стоматология', 'verbose_name_plural': 'Функциональная стоматология'},
        ),
        migrations.AlterModelOptions(
            name='implantology',
            options={'ordering': ['Implantology_IntegerField'], 'verbose_name': 'Имплантология', 'verbose_name_plural': 'Имплантология'},
        ),
        migrations.RemoveField(
            model_name='functional_dentistry',
            name='Functional_Dentistry_about',
        ),
        migrations.RemoveField(
            model_name='functional_dentistry',
            name='Functional_Dentistry_functional_dentistry',
        ),
        migrations.AddField(
            model_name='functional_dentistry',
            name='Functional_Dentistry_IntegerField',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер для ручного внесения'),
        ),
        migrations.AddField(
            model_name='functional_dentistry',
            name='Functional_Dentistry_webp',
            field=models.ImageField(blank=True, null=True, upload_to='images/Functional_Dentistry_images/webp', verbose_name='WEBP-изображение страницы Функциональная стоматология'),
        ),
        migrations.AlterField(
            model_name='functional_dentistry',
            name='Functional_Dentistry_image',
            field=models.ImageField(upload_to='images/Functional_Dentistry_images', verbose_name='Обычное изображение страницы Функциональная стоматология'),
        ),
        migrations.AlterField(
            model_name='functional_dentistry',
            name='Functional_Dentistry_title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AvitaDentApp.services', verbose_name='Название УСЛУГИ Функциональной стоматологии'),
        ),
    ]
