# Generated by Django 4.0.3 on 2022-03-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0010_alter_functional_dentistry_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Functional_Dentistry',
            new_name='FunctionalDentistry',
        ),
    ]
