# Generated by Django 4.0.3 on 2022-03-18 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0011_rename_functional_dentistry_functionaldentistry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='functionaldentistry',
            options={'ordering': ['FunctionalDentistry_IntegerField'], 'verbose_name': 'Функциональная стоматология', 'verbose_name_plural': 'Функциональная стоматология'},
        ),
        migrations.RenameField(
            model_name='functionaldentistry',
            old_name='Functional_Dentistry_IntegerField',
            new_name='FunctionalDentistry_IntegerField',
        ),
        migrations.RenameField(
            model_name='functionaldentistry',
            old_name='Functional_Dentistry_image',
            new_name='FunctionalDentistry_image',
        ),
        migrations.RenameField(
            model_name='functionaldentistry',
            old_name='Functional_Dentistry_title',
            new_name='FunctionalDentistry_title',
        ),
        migrations.RenameField(
            model_name='functionaldentistry',
            old_name='Functional_Dentistry_webp',
            new_name='FunctionalDentistry_webp',
        ),
    ]
