# Generated by Django 4.0.3 on 2022-03-18 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0012_alter_functionaldentistry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orthopedics',
            options={'ordering': ['Orthopedics_IntegerField'], 'verbose_name': 'Ортопедия', 'verbose_name_plural': 'Ортопедия'},
        ),
        migrations.RemoveField(
            model_name='orthopedics',
            name='Orthopedics_about',
        ),
        migrations.RemoveField(
            model_name='orthopedics',
            name='Orthopedics_orthopedics',
        ),
        migrations.AddField(
            model_name='orthopedics',
            name='Orthopedics_IntegerField',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер для ручного внесения'),
        ),
        migrations.AddField(
            model_name='orthopedics',
            name='Orthopedics_webp',
            field=models.ImageField(blank=True, null=True, upload_to='images/Orthopedics_images/webp', verbose_name='WEBP-изображение страницы Ортопедия'),
        ),
        migrations.AlterField(
            model_name='orthopedics',
            name='Orthopedics_image',
            field=models.ImageField(upload_to='images/Orthopedics_images', verbose_name='Обычное изображение страницы Ортопедия'),
        ),
        migrations.AlterField(
            model_name='orthopedics',
            name='Orthopedics_title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AvitaDentApp.services', verbose_name='Название УСЛУГИ Ортопедия'),
        ),
    ]
