# Generated by Django 4.0.3 on 2022-03-18 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0013_alter_orthopedics_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodontology',
            options={'ordering': ['Periodontology_IntegerField'], 'verbose_name': 'Парадонтология', 'verbose_name_plural': 'Парадонтология'},
        ),
        migrations.RemoveField(
            model_name='periodontology',
            name='Periodontology_about',
        ),
        migrations.RemoveField(
            model_name='periodontology',
            name='Periodontology_periodontology',
        ),
        migrations.AddField(
            model_name='periodontology',
            name='Periodontology_IntegerField',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер для ручного внесения'),
        ),
        migrations.AddField(
            model_name='periodontology',
            name='Periodontology_webp',
            field=models.ImageField(blank=True, null=True, upload_to='images/Periodontology_images/webp', verbose_name='WEBP-изображение страницы Парадонтология'),
        ),
        migrations.AlterField(
            model_name='periodontology',
            name='Periodontology_image',
            field=models.ImageField(upload_to='images/Periodontology_images', verbose_name='Обычное изображение страницы Парадонтология'),
        ),
        migrations.AlterField(
            model_name='periodontology',
            name='Periodontology_title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AvitaDentApp.services', verbose_name='Название УСЛУГИ Парадонтология'),
        ),
    ]
