# Generated by Django 4.0.3 on 2022-03-21 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0014_alter_periodontology_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapy',
            options={'ordering': ['Therapy_IntegerField'], 'verbose_name': 'Терапия', 'verbose_name_plural': 'Терапия'},
        ),
        migrations.RemoveField(
            model_name='therapy',
            name='Therapy_about',
        ),
        migrations.RemoveField(
            model_name='therapy',
            name='Therapy_therapy',
        ),
        migrations.AddField(
            model_name='therapy',
            name='Therapy_IntegerField',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер для ручного внесения'),
        ),
        migrations.AddField(
            model_name='therapy',
            name='Therapy_webp',
            field=models.ImageField(blank=True, null=True, upload_to='images/Therapy_images/webp', verbose_name='WEBP-изображение страницы Терапия'),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='Therapy_image',
            field=models.ImageField(upload_to='images/Therapy_images', verbose_name='Обычное изображение страницы Терапия'),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='Therapy_title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AvitaDentApp.services', verbose_name='Название УСЛУГИ Терапия'),
        ),
    ]
