# Generated by Django 4.0.3 on 2022-03-21 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0015_alter_therapy_options_remove_therapy_therapy_about_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surgery',
            options={'ordering': ['Surgery_IntegerField'], 'verbose_name': 'Хирургия', 'verbose_name_plural': 'Хирургия'},
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='Surgery_about',
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='Surgery_surgery',
        ),
        migrations.AddField(
            model_name='surgery',
            name='Surgery_IntegerField',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер для ручного внесения'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='Surgery_webp',
            field=models.ImageField(blank=True, null=True, upload_to='images/Surgery_images/webp', verbose_name='WEBP-изображение страницы Хирургия'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='Surgery_image',
            field=models.ImageField(upload_to='images/Surgery_images', verbose_name='Обычное изображение страницы Хирургия'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='Surgery_title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AvitaDentApp.services', verbose_name='Название УСЛУГИ Хирургия'),
        ),
    ]
