# Generated by Django 4.0.3 on 2022-03-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0016_alter_surgery_options_remove_surgery_surgery_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='Doctors_middle_name',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='Doctors_surname',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='Doctors_about',
            field=models.CharField(max_length=1000, verbose_name='О докторе'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='Doctors_name',
            field=models.CharField(max_length=100, verbose_name='Ф.И.О. доктора'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='Doctors_photo',
            field=models.ImageField(upload_to='images/doctors_images', verbose_name='Фотография доктора'),
        ),
    ]
