# Generated by Django 4.0.3 on 2022-03-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0017_remove_doctors_doctors_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctors',
            options={'ordering': ['id'], 'verbose_name': 'Доктора', 'verbose_name_plural': 'Доктора'},
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='Doctors_photo',
        ),
        migrations.AddField(
            model_name='doctors',
            name='Doctors_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Doctors_images', verbose_name='Обычное изображение доктора'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='Doctors_webp',
            field=models.ImageField(blank=True, null=True, upload_to='images/Doctors_images/webp', verbose_name='WEBP-изображение доктора'),
        ),
    ]
