# Generated by Django 4.0.3 on 2022-03-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0018_alter_doctors_options_remove_doctors_doctors_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Feedback_phone',
            field=models.CharField(max_length=18),
        ),
    ]
