# Generated by Django 4.0.3 on 2022-03-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0019_alter_feedback_feedback_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certificates_title', models.CharField(max_length=100)),
                ('Certificates_webp', models.ImageField(upload_to='images/Certificates_images/webp', verbose_name='WEBP-изображение Сертификата')),
                ('Certificates_image', models.ImageField(upload_to='images/Certificates_images', verbose_name='Обычное изображение Сертификата')),
            ],
            options={
                'verbose_name': 'Сертификаты',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['id'],
            },
        ),
    ]
