# Generated by Django 4.0.3 on 2022-03-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0023_licenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Appointment_name', models.CharField(max_length=50)),
                ('Appointment_phone', models.CharField(max_length=18)),
                ('Appointment_mail', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Запись на приём',
                'verbose_name_plural': 'Запись на приём',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Make_An_Appointment',
        ),
    ]
