# Generated by Django 4.0.3 on 2022-03-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0025_alter_appointment_appointment_mail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Appointment_mail',
            new_name='Appointment_email',
        ),
    ]
