# Generated by Django 4.0.3 on 2022-03-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0027_alter_instagram_links_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram_links',
            name='Instagram_Links_webp',
            field=models.ImageField(blank=True, null=True, upload_to='images/instagram_links_images/webp', verbose_name='WEBP-изображение Instagram-блока'),
        ),
        migrations.AlterField(
            model_name='instagram_links',
            name='Instagram_Links_images',
            field=models.ImageField(upload_to='images/instagram_links_images', verbose_name='Обычное изображение Instagram-блока'),
        ),
        migrations.AlterField(
            model_name='instagram_links',
            name='Instagram_Links_link',
            field=models.URLField(max_length=1000, verbose_name='Ссылка на страницу в Instagram'),
        ),
        migrations.AlterField(
            model_name='instagram_links',
            name='Instagram_Links_title',
            field=models.CharField(max_length=200, verbose_name='Название Instagram-блока'),
        ),
    ]
