# Generated by Django 4.0.3 on 2022-03-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0028_instagram_links_instagram_links_webp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagram_links',
            old_name='Instagram_Links_images',
            new_name='Instagram_Links_image',
        ),
    ]
