# Generated by Django 4.0.3 on 2022-07-12 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0029_rename_instagram_links_images_instagram_links_instagram_links_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagram_links',
            options={'ordering': ['id'], 'verbose_name': 'Наш Instagram', 'verbose_name_plural': 'Наш Instagram'},
        ),
    ]
