# Generated by Django 4.0.3 on 2022-03-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0002_alter_stocks_stocks_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='Stocks_gallery',
            field=models.ImageField(upload_to='images/stocks_gallery_images'),
        ),
    ]
