# Generated by Django 4.0.3 on 2022-03-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0007_alter_actions_actions_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['id'], 'verbose_name': 'Услуги', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.RenameField(
            model_name='services',
            old_name='Services_functional_dentistry',
            new_name='Services_title',
        ),
        migrations.RemoveField(
            model_name='services',
            name='Services_implantology',
        ),
        migrations.RemoveField(
            model_name='services',
            name='Services_orthodontics',
        ),
        migrations.RemoveField(
            model_name='services',
            name='Services_orthopedics',
        ),
        migrations.RemoveField(
            model_name='services',
            name='Services_periodontology',
        ),
        migrations.RemoveField(
            model_name='services',
            name='Services_surgery',
        ),
        migrations.RemoveField(
            model_name='services',
            name='Services_therapy',
        ),
    ]
