# Generated by Django 4.0.3 on 2022-03-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0010_alter_services_services_webp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Feedback_phone',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
