# Generated by Django 4.0.3 on 2022-03-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvitaDentApp', '0012_alter_feedback_feedback_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Feedback_phone',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
